# Generated by Django 2.1.5 on 2019-01-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('social_media_Link', models.CharField(choices=[('Ld', 'Linkedin'), ('Fb', 'Facebook'), ('Tw', 'Twitter')], max_length=150)),
                ('job_title', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(upload_to='employees')),
            ],
        ),
    ]
