# Generated by Django 2.1.5 on 2019-01-13 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChildrensSchoolLives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='social_media_Type',
            field=models.CharField(choices=[('Ld', 'Linkedin'), ('Fb', 'Facebook'), ('Tw', 'Twitter')], default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_media_Link',
            field=models.CharField(max_length=250),
        ),
    ]
