# Generated by Django 2.1.5 on 2019-01-13 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChildrensSchoolLives', '0002_auto_20190113_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='social_media_Link',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='social_media_Type',
        ),
        migrations.AddField(
            model_name='employee',
            name='Linkedin_Link',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
