# Generated by Django 2.1.5 on 2019-05-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildrensSchoolLives', '0004_auto_20190113_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WebsitePhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
