# Generated by Django 2.1.5 on 2019-06-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildrensSchoolLives', '0008_numberofschoolsinconnacht_numberofschoolsinleinster_numberofschoolsinmunster_numberofschoolsinulster'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('data_post_expires', models.DateField()),
                ('about', models.TextField()),
                ('requirements', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='social_media_Link',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='social_media_Type',
        ),
    ]
