# Generated by Django 2.1.5 on 2019-06-13 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChildrensSchoolLives', '0009_auto_20190612_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_about_area',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
